from graphics import *
import time
win = GraphWin("storacnox cragir",800,600)
tx=Text(Point(400,200),"BAREV IM QAJ")
tx.setSize(20)
tx.draw(win)
time.sleep(2)
tx.undraw()
time.sleep(2)
tx=Text(Point(400,200),"sksenq xax@???")
strok="sksenq xax@???"
tx.setSize(20)
tx.draw(win)
cx=Text(Point(200,400),"HA")
cx.setSize(20)
cx.draw(win)
fx=Text(Point(600,400),"CHE")
fx.setSize(20)
fx.draw(win)
rect=Rectangle(Point(150,350),Point(250,450))
rect.draw(win)
sekt=Rectangle(Point(550,350),Point(650,450))
sekt.draw(win)
while True:
     p=win.getMouse()
     x=p.x
     y=p.y
     print(x,y)
     if x>149 and x<251 and y>349 and y<451:
         tx.undraw()
         rect.undraw()
         sekt.undraw()
         fx.undraw()
         cx.undraw()
         tx=Text(Point(400,200),"HMI BACEM XAXA")
         tx.setSize(20)
         tx.draw(win)
         time.sleep(3)
         tx.undraw()
         tx=Text(Point(400,200),"xaxi het em urish ban chmtaces")
         tx.setSize(20)
         tx.draw(win)
     elif x>549 and x<651 and y>349 and y<451:
         tx.undraw()
         rect.undraw()
         sekt.undraw()
         fx.undraw()
         cx.undraw()
         tx=Text(Point(400,200),"Duduk tam  pche")
         tx.setSize(20)
         tx.draw(win)
         time.sleep(3)
         tx.undraw()
         tx=Text(Point(400,200),"iskakan duduki het em urish ban chmtaces")
         tx.setSize(20)
         tx.draw(win)
         time.sleep(3)
         tx.undraw()
         point=Image(Point(400,300),"/home/David/Desktop/duduk.png")
         point.draw(win)
     else:
         photo=Image(Point(400,300),"/home/David/Desktop/clipart214416.png")
         photo.draw(win)
         time.sleep(1)
         photo.undraw()
